### ISSUE TITLE
Error building site: POSTCSS: failed to transform "css/hb.css" (text/css): /home/ubunmac/dev/blog/node_modules/yaml/dist/compose/composer.js:33 with hugu-extended v0.111.3 

### ISSUE THREAD

**Issue by johnsmithodom** [hbstack/blog#120]
npm run dev

> dev
> hugo server --gc --disableFastRender --enableGitInfo -D

Start building sites … 
hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended linux/amd64 BuildDate=2023-03-12T11:40:50Z VendorInfo=gohugoio
Error: Error building site: POSTCSS: failed to transform "css/hb.css" (text/css): /home/ubunmac/dev/blog/node_modules/yaml/dist/compose/composer.js:33
                if (prelude[i + 1]?.[0] !== '#')
                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ubunmac/dev/blog/node_modules/yaml/dist/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Built in 89443 ms

**Comment by razonyang** [comment]
What is the Node.js version? Should work with `>=16`, not sure if this is a Node.js version issue.
